#Configurações para o Task Manager API - DOCKER

version: '3.8'

services:
 postgres:
   image: postgres:latest
   container_name: taskmanager_postgres
   restart: always
   ports:
     - "5432:5432"
   environment:
     POSTGRES_DB: task_manager_db
     POSTGRES_USER: root
     POSTGRES_PASSWORD: root_password
   volumes:
     - pgdata:/var/lib/postgresql/data