spring:
  application:
    name: task-manager-api
server:
  port: 9191

#Database configuration
datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db
    username: root
    password: root_password
    driver-class-name: org.postgresql.Driver

  # JPA configuration
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging configuration
logging:
  level:
    root: INFO

